services:
  db:
    image: postgres:13.3
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASS}"
      POSTGRES_DB: "${PG_DB}"
    ports:
      - 5433:5433
    networks:
      - botnet
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init_scripts.sql:/docker-entrypoint-initdb.d
  bot:
    container_name: imager
    build: 
      context: .
    command: bash -c "python handlers/db_definition.py && python handlers/main.py"
      
    restart: always
    image: imager
    networks:
      - botnet
    depends_on:
      - db
    volumes:
      - .:/src
    environment:
      DB_HOST: db
      DB_PORT: 5433
      DB_USER: "${PG_USER}"
      DB_PASSWORD: "${PG_PASS}"
volumes:
  db:
    driver: local
networks:
  botnet:
    driver: bridge